### ISSUE TITLE
chore(dropdowns): not working with minified version

### ISSUE THREAD

**Issue by jotdl** [valor-software/ngx-bootstrap#100]
Hey,

I tried ng2-bootstrap today and wanted to use dropdowns without any luck.
The following html 

```
html
<li class="dropdown" dropdown>
  <a class="dropdown-toggle" dropdownToggle>A <span class="caret"></span></a>
  <ul dropdownMenu class="dropdown-menu">
    <li><a [routerLink]="['/B']">B</a></li>
    <li role="separator" class="divider"></li>
    <li><a class="disabled" [routerLink]="['/C']">C</a></li>
  </ul>
</li>
```

_does not_ work with `../node_modules/ng2-bootstrap/bundles/ng2-bootstrap.min.js` but _does work_ with `../node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js`.

I get the follwoing exception

```
EXCEPTION: No provider for a! (a -> a)BrowserDomAdapter.logError @ angular2.dev.js:22690BrowserDomAdapter.logGroup @ angular2.dev.js:22701ExceptionHandler.call @ angular2.dev.js:1163(anonymous function) @ angular2.dev.js:12416NgZone._notifyOnError @ angular2.dev.js:13324collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13228run @ angular2-polyfills.js:141(anonymous function) @ angular2.dev.js:13247zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243microtask @ angular2.dev.js:13279run @ angular2-polyfills.js:138(anonymous function) @ angular2.dev.js:13247zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2.dev.js:22690 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:22690ExceptionHandler.call @ angular2.dev.js:1165(anonymous function) @ angular2.dev.js:12416NgZone._notifyOnError @ angular2.dev.js:13324collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13228run @ angular2-polyfills.js:141(anonymous function) @ angular2.dev.js:13247zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243microtask @ angular2.dev.js:13279run @ angular2-polyfills.js:138(anonymous function) @ angular2.dev.js:13247zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2.dev.js:22690 Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:8080/node_modules/angular2/bundles/angular2.dev.js:7070:21)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:8080/node_modules/angular2/bundles/angular2.dev.js:1627:14)
```

Moreover I am using _system.js_.

Any suggestions?

**Comment by valorkin** [comment]
sorry for it, this is known beta.1 issue for minified  version
can you create a plunker for it? may be I can fix it somehow

**Comment by valorkin** [comment]
it seems that meta notations lost, I should add `@Inject()` may be will help

**Comment by jotdl** [comment]
Hi,
Sorry, was on vacation.
Will recheck this issue this weekend and hopefully submit a plunker, too.

**Comment by valorkin** [comment]
if you use minified version turn of `mangle`
ng2 beta doesn't play nice with minification

**Comment by jayhahn** [comment]
If I use the non-min version, I get 

No provider for Dropdown! (DropdownToggle -> Dropdown)

instead...

**Comment by Dinistro** [comment]
@jayhahn Did you add the `dropdown` on that parrent taag of the one with `dropdownToggle`?

```
<div class="btn-group" dropdown><!-- This is important!-->
  <button type="button" class="btn" dropdownToggle>Simple Dropdown</button>
  <ul class="dropdown-menu" role="menu">
    <li role="menuitem"><a class="dropdown-item" href="#">Action</a></li>
    <li class="divider dropdown-divider"></li>
    <li role="menuitem"><a class="dropdown-item" href="#">Separated link</a></li>
  </ul>
</div>
```
