### ISSUE TITLE
not compatible with ng-xi18n

### ISSUE THREAD

**Issue by NgxDev** [valor-software/ngx-bootstrap#1060]
trying to run `./node_modules/.bin/ng-xi18n` gives:

```
Error: Unexpected value 'Ng2BootstrapModule' imported by the module 'AppModule'
    at D:\projects\ng2-app\node_modules\@angular\compiler\bundles\compiler.umd.js:14109:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (D:\projects\ng2-app\node_modules\@angular\compiler\bundles\compiler.umd.js:14094:46)
    at D:\projects\ng2-app\node_modules\@angular\compiler\bundles\compiler.umd.js:12936:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (D:\projects\ng2-app\node_modules\@angular\compiler\bundles\compiler.umd.js:12935:21)
    at Extractor.extract (D:\projects\ng2-app\node_modules\@angular\compiler-cli\src\extract_i18n.js:92:47)
    at extract (D:\projects\ng2-app\node_modules\@angular\compiler-cli\src\extract_i18n.js:16:35)
    at Object.main (D:\projects\ng2-app\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (D:\projects\ng2-app\node_modules\@angular\compiler-cli\src\extract_i18n.js:160:9)
Extraction failed
```

**Comment by valorkin** [comment]
no metadata, duplicated issue
but fixed anyway :)
