### ISSUE TITLE
Can't get to work pagination module

### ISSUE THREAD

**Issue by vheathen** [valor-software/ngx-bootstrap#1210]
It's really weird, but I can't force pagination module working.

ng2-bootstrap version: 1.1.16
ng2 version: 2.1.1

app.module.ts:
```
import { NgModule } from '@angular/core';
import {
  FormsModule,
  ReactiveFormsModule
} from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import {
  routing,
  appRoutingProviders
} from './app.routing';
import ApplicationComponent from './application/application.component';
import HomeComponent from './pages/home/home.component';
import FooterComponent from './common/components/footer/footer.component';
import NavbarComponent from './common/components/navbar/navbar.component';
import PageHeaderComponent from './common/components/page-header/page-header.component';
import SearchPanelComponent from './common/components/search-panel/search-panel.component';
import {
  CollapseModule,
  PaginationModule
} from 'ng2-bootstrap';
import LastNioktrComponent from './common/components/last-nioktr/last-nioktr.component';
import { NioktrService } from './common/services/nioktr.service';
import SearchIpoComponent from './pages/search-ipo/search-ipo.component';
import { SearchIpoService } from './common/services/search-ipo.service';
import SearchItemNioktrComponent from './pages/search-ipo/search-item-nioktr.component';
import NioktrShowComponent from './pages/ipo/nioktr/nioktr-detail.component';

@NgModule({
            imports:      [
              BrowserModule,
              HttpModule,
              FormsModule,
              ReactiveFormsModule,
              routing,
              PaginationModule,
              CollapseModule
            ],
            declarations: [
              ...skipped...
              LastNioktrComponent,
              SearchIpoComponent,
              ...skipped...
            ],
            providers:    [
              // { provide: LOCALE_ID, useValue: 'fr' },
              appRoutingProviders,
              NioktrService,
              SearchIpoService
            ],
            bootstrap:    [ApplicationComponent]
          })

export class AppModule {
}
```

html template of SearchIpoComponent:
```
<ias-search-panel></ias-search-panel>

<p *ngIf="docsCount != null">{{docsCount}} documents found</p>

<div class="center-fix" *ngIf="isInProgress">
  <h4>Data is loading, please wait...</h4>
  <i class="main-spinner fa fa-spin fa-spinner"></i>
</div>


<pagination [boundaryLinks]="true"
            [totalItems]="itemsCount"
            [maxSize]="15"
            [itemsPerPage]="itemsPerPage"
            (pageChanged)="pageChanged($event)"

            class="pagination-sm"
            previousText="&lsaquo;"
            nextText="&rsaquo;"
            firstText="&laquo;"
            lastText="&raquo;"></pagination>

<div *ngIf="!isInProgress">

  <div class="search-item-ipo" *ngFor="let doc of ipoList">
    <ias-search-item-nioktr [data]="doc"></ias-search-item-nioktr>
  </div>
</div>
```

I always get this error:
```
zone.js:390 Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'boundaryLinks' since it isn't a known property of 'pagination'. ("


<pagination [ERROR ->][boundaryLinks]="true"
            [totalItems]="itemsCount"
            [maxSize]="15"
"): SearchIpoComponent@11:12
Can't bind to 'totalItems' since it isn't a known property of 'pagination'. ("

<pagination [boundaryLinks]="true"
            [ERROR ->][totalItems]="itemsCount"
            [maxSize]="15"
            [itemsPerPage]="itemsPerPage"
"): SearchIpoComponent@12:12
Can't bind to 'maxSize' since it isn't a known property of 'pagination'. ("
<pagination [boundaryLinks]="true"
            [totalItems]="itemsCount"
            [ERROR ->][maxSize]="15"
            [itemsPerPage]="itemsPerPage"
            (pageChanged)="pageChanged($even"): SearchIpoComponent@13:12
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'. ("
            [totalItems]="itemsCount"
            [maxSize]="15"
            [ERROR ->][itemsPerPage]="itemsPerPage"
            (pageChanged)="pageChanged($event)"

"): SearchIpoComponent@14:12
'pagination' is not a known element:
1. If 'pagination' is an Angular component, then verify that it is part of this module.
2. If 'pagination' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<pagination [boundaryLinks]="true"
            [totalItems]="itemsCount"
            [maxSize]="15"
"): SearchIpoComponent@11:0
Error: Template parse errors:
Can't bind to 'boundaryLinks' since it isn't a known property of 'pagination'. ("


<pagination [ERROR ->][boundaryLinks]="true"
            [totalItems]="itemsCount"
            [maxSize]="15"
"): SearchIpoComponent@11:12
Can't bind to 'totalItems' since it isn't a known property of 'pagination'. ("

<pagination [boundaryLinks]="true"
            [ERROR ->][totalItems]="itemsCount"
            [maxSize]="15"
            [itemsPerPage]="itemsPerPage"
"): SearchIpoComponent@12:12
Can't bind to 'maxSize' since it isn't a known property of 'pagination'. ("
<pagination [boundaryLinks]="true"
            [totalItems]="itemsCount"
            [ERROR ->][maxSize]="15"
            [itemsPerPage]="itemsPerPage"
            (pageChanged)="pageChanged($even"): SearchIpoComponent@13:12
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'. ("
            [totalItems]="itemsCount"
            [maxSize]="15"
            [ERROR ->][itemsPerPage]="itemsPerPage"
            (pageChanged)="pageChanged($event)"

"): SearchIpoComponent@14:12
'pagination' is not a known element:
1. If 'pagination' is an Angular component, then verify that it is part of this module.
2. If 'pagination' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<pagination [boundaryLinks]="true"
            [totalItems]="itemsCount"
            [maxSize]="15"
"): SearchIpoComponent@11:0
    at TemplateParser.parse (http://localhost:3300/vendor.js:25810:19)
    at RuntimeCompiler._compileTemplate (http://localhost:3300/vendor.js:45538:51)
    at http://localhost:3300/vendor.js:45443:83
    at Set.forEach (native)
    at compile (http://localhost:3300/vendor.js:45443:47)
    at ZoneDelegate.invoke (http://localhost:3300/polyfills.js:16179:26)
    at Zone.run (http://localhost:3300/polyfills.js:16061:43)
    at http://localhost:3300/polyfills.js:16449:57
    at ZoneDelegate.invokeTask (http://localhost:3300/polyfills.js:16212:35)
    at Zone.runTask (http://localhost:3300/polyfills.js:16101:47)
    at drainMicroTaskQueue (http://localhost:3300/polyfills.js:16348:35)
    at TemplateParser.parse (http://localhost:3300/vendor.js:25810:19)
    at RuntimeCompiler._compileTemplate (http://localhost:3300/vendor.js:45538:51)
    at http://localhost:3300/vendor.js:45443:83
    at Set.forEach (native)
    at compile (http://localhost:3300/vendor.js:45443:47)
    at ZoneDelegate.invoke (http://localhost:3300/polyfills.js:16179:26)
    at Zone.run (http://localhost:3300/polyfills.js:16061:43)
    at http://localhost:3300/polyfills.js:16449:57
    at ZoneDelegate.invokeTask (http://localhost:3300/polyfills.js:16212:35)
    at Zone.runTask (http://localhost:3300/polyfills.js:16101:47)
    at drainMicroTaskQueue (http://localhost:3300/polyfills.js:16348:35)
    at resolvePromise (http://localhost:3300/polyfills.js:16415:31)
    at resolvePromise (http://localhost:3300/polyfills.js:16400:17)
    at http://localhost:3300/polyfills.js:16449:17
    at ZoneDelegate.invokeTask (http://localhost:3300/polyfills.js:16212:35)
    at Zone.runTask (http://localhost:3300/polyfills.js:16101:47)
    at drainMicroTaskQueue (http://localhost:3300/polyfills.js:16348:35)
```

The most weird thing is that <collapse> directive works well in another component (ias-search-panel).

I really stuck. The problem should be in something pretty trivial, but I can't understand what's going on. Thanks a lot in advance!

**Comment by vheathen** [comment]
Ok, I had caught the problem. I don't need a variable to be linked with ngModel since I'm using event-driven function, so I omitted [(ngModel]). But this component can't work without it. 

Thanks anyway!

**Comment by teraldo79** [comment]
I am having a similar issue with the ng2-table demo, where it wont recognize 'maxSize','itemsPerPage' and 'totalItems' as properties pf Pagination. However, I followed the example pretty closely, and i do not have an ngModel declared on the markup. 

Can i reopen this issue?
