### ISSUE TITLE
chore(webpack): undefined is not a valid test

### ISSUE THREAD

**Issue by SebastianPozoga** [valor-software/ngx-bootstrap#125]
I can problem when i try build app. Source of problem is 'webpack --progress --color' command. When i use:
npm run-script start

I take error

```
npm ERR! Linux 3.16.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dev"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ng2-bootstrap@1.0.2-beta.0 build:dev: `NODE_ENV=production webpack --progress --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-bootstrap@1.0.2-beta.0 build:dev script 'NODE_ENV=production webpack --progress --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --progress --color
npm ERR! You can get their info via:
npm ERR!     npm owner ls ng2-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sebastian/dev/ng2-bootstrap/npm-debug.log

npm ERR! Linux 3.16.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ng2-bootstrap@1.0.2-beta.0 start: `npm run build:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-bootstrap@1.0.2-beta.0 start script 'npm run build:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls ng2-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sebastian/dev/ng2-bootstrap/npm-debug.log
```

**/home/sebastian/dev/ng2-bootstrap/npm-debug.log:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng2-bootstrap@1.0.2-beta.0~prestart: ng2-bootstrap@1.0.2-beta.0
6 silly lifecycle ng2-bootstrap@1.0.2-beta.0~prestart: no script for prestart, continuing
7 info lifecycle ng2-bootstrap@1.0.2-beta.0~start: ng2-bootstrap@1.0.2-beta.0
8 verbose lifecycle ng2-bootstrap@1.0.2-beta.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng2-bootstrap@1.0.2-beta.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/sebastian/dev/ng2-bootstrap/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
10 verbose lifecycle ng2-bootstrap@1.0.2-beta.0~start: CWD: /home/sebastian/dev/ng2-bootstrap
11 silly lifecycle ng2-bootstrap@1.0.2-beta.0~start: Args: [ '-c', 'npm run build:dev' ]
12 silly lifecycle ng2-bootstrap@1.0.2-beta.0~start: Returned: code: 1  signal: null
13 info lifecycle ng2-bootstrap@1.0.2-beta.0~start: Failed to exec start script
14 verbose stack Error: ng2-bootstrap@1.0.2-beta.0 start: `npm run build:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ng2-bootstrap@1.0.2-beta.0
16 verbose cwd /home/sebastian/dev/ng2-bootstrap
17 error Linux 3.16.0-39-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error ng2-bootstrap@1.0.2-beta.0 start: `npm run build:dev`
22 error Exit status 1
23 error Failed at the ng2-bootstrap@1.0.2-beta.0 start script 'npm run build:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng2-bootstrap package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:dev
23 error You can get their info via:
23 error     npm owner ls ng2-bootstrap
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**webpack --progress --color**

```
$ webpack --progress --color
 70% 2/2 build modules/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:48
        throw new Error(test + " is not a valid test");
        ^

Error: undefined is not a valid test
    at asMatcher (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:48:9)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:37:12
    at Array.map (native)
    at asMatcher (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:28:23)
    at LoadersList.matchPart (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:65:16)
    at LoadersList.matchObject (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:94:11)
    at LoadersList.<anonymous> (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:77:12)
    at Array.map (native)
    at LoadersList.match (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:70:19)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:112:71
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:726:13
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:52:16
    at done (/home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:246:17)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:44:16
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:723:17
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:167:37
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
    at onResolved (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at innerCallback (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:89:22)
    at loggingCallbackWrapper (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/tapable/lib/Tapable.js:134:6
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:55:11
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:46:14
    at loggingCallbackWrapper (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/tapable/lib/Tapable.js:134:6
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:123:21
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
    at loggingCallbackWrapper (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
sebastian@sebastian-ThinkPad-L440:~/dev/ng2-bootstrap$ 
sebastian@sebastian-ThinkPad-L440:~/dev/ng2-bootstrap$ webpack --progress --color
 70% 2/2 build modules/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:48
        throw new Error(test + " is not a valid test");
        ^

Error: undefined is not a valid test
    at asMatcher (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:48:9)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:37:12
    at Array.map (native)
    at asMatcher (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:28:23)
    at LoadersList.matchPart (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:65:16)
    at LoadersList.matchObject (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:94:11)
    at LoadersList.<anonymous> (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:77:12)
    at Array.map (native)
    at LoadersList.match (/home/sebastian/dev/ng2-bootstrap/node_modules/webpack-core/lib/LoadersList.js:70:19)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:112:71
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:726:13
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:52:16
    at done (/home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:246:17)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:44:16
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:723:17
    at /home/sebastian/dev/ng2-bootstrap/node_modules/async/lib/async.js:167:37
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
    at onResolved (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at innerCallback (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:89:22)
    at loggingCallbackWrapper (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/tapable/lib/Tapable.js:134:6
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:55:11
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:46:14
    at loggingCallbackWrapper (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/sebastian/dev/ng2-bootstrap/node_modules/tapable/lib/Tapable.js:134:6
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:123:21
    at /home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
    at loggingCallbackWrapper (/home/sebastian/dev/ng2-bootstrap/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
```

I use npm v5.5.0
(and I tested it on 4.x and take the some error)

**Comment by valorkin** [comment]
yeap, I know, I will be fixing today

**Comment by valorkin** [comment]
hey, he were go
https://travis-ci.org/valor-software/ng2-bootstrap/builds/106547156
