### ISSUE TITLE
feat(tabs): remove ngTransclude

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [valor-software/ngx-bootstrap#1314]
i use angular-cli and i want <code>i18n</code>tag can generate translate file.

when run command ng-xi18n, its error like follow:
```
D:\Code\WebstormProjects\JWFrontPage>"./node_modules/.bin/ng-xi18n"
Error: Cannot determine the module for class NgTranscludeDirective in D:/Code/WebstormProjects/JWFrontPage/node_modules/ng2-bootstrap/components/common.d.ts!
    at Object.analyzeAndValidateNgModules (D:\Code\WebstormProjects\JWFrontPage\node_modules\@angular\compiler\bundles\compiler.umd.js:12707:17)

    at Extractor.extract (D:\Code\WebstormProjects\JWFrontPage\node_modules\@angular\compiler-cli\src\extractor.js:33:27)
    at extract (D:\Code\WebstormProjects\JWFrontPage\node_modules\@angular\compiler-cli\src\extract_i18n.js:19:35)
    at Object.main (D:\Code\WebstormProjects\JWFrontPage\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (D:\Code\WebstormProjects\JWFrontPage\node_modules\@angular\compiler-cli\src\extract_i18n.js:46:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Extraction failed
```

it seems like angularjs applicability question?

version:
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: win32 x64
npm: 3.10.8
ng2-bootstrap: 1.1.16

**Comment by valorkin** [comment]
it is used only in tabs module...

**Comment by valorkin** [comment]
need to cut this out, I did it when ng-content did not existed ;)
