### ISSUE TITLE
AoT compilation in Angular-2 with DropdownModule

### ISSUE THREAD

**Issue by Mage111** [valor-software/ngx-bootstrap#1350]
This happens when using AoT compilation in Angular 2.

When I try to run ngc, it errors out as following:

C:\>"node_modules/.bin/ngc"  `"tsconfig-aot.json"`

`Error: Unexpected value 'DropdownModule' imported by the module 'SharedModule'
    at ..\node_modules\@angular\compiler\bundles\compiler.umd.js:17768:46
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (..\node_modules\@angular\compiler\bundles\compiler.umd.js:17753:51)
    at addNgModule (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24349:60)
    at ..\node_modules\@angular\compiler\bundles\compiler.umd.js:24360:16
    at Array.forEach (native)
    at _createNgModules (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24359:28)
    at analyzeNgModules (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24238:16)
    at analyzeAndValidateNgModules (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24248:37)
    at AotCompiler.compileAll (..\node_modules\@angular\compiler\bundles\compiler.umd.js:23987:20)`

I believe it has resemblance to the issue [#70](https://github.com/gevgeny/angular2-highcharts/issues/70)

the metadata.json files are missing from the library which are required by ngc.
I'm using latest angular-cli.

Can those missing files be added soon?
Thanks.

**Comment by valorkin** [comment]
Those files available in latest version
Here is docs for it http://valorkin.github.io/ng2-bootstrap/#/dropdowns
BTW docs compiled with AoT
PS try to use angular-cli

**Comment by valorkin** [comment]
Latest is 1.1.16-7
