### ISSUE TITLE
AOT Timepicker error

### ISSUE THREAD

**Issue by quiringk** [valor-software/ngx-bootstrap#1370]
I am getting this error when building AOT

```
Error: Error at C:/Projects/NeilKellyClient4/aot/node_modules/ng2-bootstrap/timepicker/timepicker.component.ngfactory.ts:650:35: Supplied parameters do not match any signature of call target.
Error at C:/Projects/NeilKellyClient4/aot/node_modules/ng2-bootstrap/timepicker/timepicker.component.ngfactory.ts:668:35: Supplied parameters do not match any signature of call target.
    at check (C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

Is there something I need to do in order to make this work for timepicker? Here is what my timepicker template code looks like: (I tried both (ngModelChange) and (change) but both didn't work)

`<timepicker [(ngModel)]="date2" (change)="timeChanged()" [hourStep]="1" [minuteStep]="15"></timepicker>
`

**Comment by valorkin** [comment]
fix published as 16-8

**Comment by quiringk** [comment]
@valorkin  Still getting same error with 16-8

```
Error: Error at C:/Projects/NeilKellyClient4/aot/node_modules/ng2-bootstrap/timepicker/timepicker.component.ngfactory.ts:650:35: Supplied parameters do not match any signature of call target.
Error at C:/Projects/NeilKellyClient4/aot/node_modules/ng2-bootstrap/timepicker/timepicker.component.ngfactory.ts:668:35: Supplied parameters do not match any signature of call target.
    at check (C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

**Comment by valorkin** [comment]
http://stackoverflow.com/questions/34405301/detect-change-to-ngmodel-on-a-select-tag-angular-2
it is nothing to do with timepicker
in worst case wrap date2 with {get;set;}

**Comment by valorkin** [comment]
you forget to provide `$event`
`(ngModelChange)="onChange($event)"`

**Comment by philjones88** [comment]
@valorkin I know you merged my PR. I updated but it's still error'ing on the same lines? Was the change in 16-8?

**Comment by valorkin** [comment]
it should be... please check
https://unpkg.com/ng2-bootstrap@1.1.16-8/timepicker/

**Comment by philjones88** [comment]
@valorkin nope `hoursOnBlur($event)` is inside https://unpkg.com/ng2-bootstrap@1.1.16-8/timepicker/timepicker.component.js and probably the other files too

**Comment by valorkin** [comment]
may be publishing at 4am was not so good idea

**Comment by valorkin** [comment]
@philjones88 what versions do you using for AoT compilation?
demo pages build without such issues

**Comment by philjones88** [comment]
@valorkin latest. 2.4.0

**Comment by valorkin** [comment]
mm

**Comment by valorkin** [comment]
@philjones88 try 1.1.16-9

**Comment by philjones88** [comment]
@valorkin works :) 👍

**Comment by valorkin** [comment]
awesome
just in case, DM in slack if something urgent
https://ngx-slack.herokuapp.com/
