### ISSUE TITLE
Import ModalDirective filepath different for JIT vs. AOT in order to work (Angular 2.4.2)

### ISSUE THREAD

**Issue by quiringk** [valor-software/ngx-bootstrap#1450]
I just upgraded to Angular 2.4.2 from 2.2.3. 

I import ModalDirective in my components in order to use them with @ViewChild. Before upgrading, I used this import statement and everything worked fine:

`import { ModalDirective } from 'ng2-bootstrap/ng2-bootstrap'`

But after upgrading, I was getting AOT compilation errors like:

`'ModalDirective' is not exported by node_modules\ng2-bootstrap\ng2-bootstrap.js`

In order to get the AOT to compile I had to modify the import statement to:

`import { ModalDirective } from 'ng2-bootstrap/modal/modal.component';`

But then my JIT development compilation started failing like so:

`zone.js:1382 GET http://localhost:3000/ng2-bootstrap/modal/modal.component.js 404 (Not Found)`

So now, I have to comment out back and forth when switching between the two different compilations

**Comment by jordanluyke** [comment]
Worked for me when I added ModalDirective to my Rollup namedExports

``
'node_modules/ng2-bootstrap/index.js': ['DropdownModule', 'ModalModule', 'PaginationModule', 'ModalDirective'],
``

**Comment by valorkin** [comment]
It should work as `import { ModalDirective } from 'ng2-bootstrap'`

**Comment by valorkin** [comment]
@quiringk drop me a note if it did not helped

**Comment by quiringk** [comment]
@valorkin it didn't work for me. I tried combinations of everything above. Still am doing what I had to in my first comment above. Not a huge deal because I can keep doing commenting/uncommenting for AOT. Maybe it has something to do with me still using systemjs?

systemjs.config.js:

`'ng2-bootstrap/ng2-bootstrap':'npm:ng2-bootstrap/bundles/ng2-bootstrap.umd.js',`

`'ng2-bootstrap': {
        defaultExtension: 'js'
      },`

I tried changing the ng2-bootstrap/ng2-bootstrap to just ng2-bootstrap but then it stopped working.

**Comment by valorkin** [comment]
Yes, here is the issue root cause!
Please compare it to config here: https://github.com/valor-software/angular2-quickstart

**Comment by quiringk** [comment]
Still didn't work. I changed all my imports to

`import { ModalDirective } from 'ng2-bootstrap';`

and here is my systemjs config:

```
/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 * Override at the last minute with global.filterSystemConfig (as plunkers do)
 */
(function(global) {
  System.config({
    // "defaultJSExtensions":true,
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
     // map tells the System loader where to look for things
    map: {
       // our app is within the app folder
      app: 'app',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
       // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',
      'moment':                    'npm:ng2-bootstrap/node_modules/moment/moment',
      'ng2-bootstrap':             'npm:ng2-bootstrap',
      'primeng':                   'npm:primeng',
      'pdfjs-dist':                'npm:pdfjs-dist',
      'angular2-toaster':          'npm:angular2-toaster',
      'css-element-queries':       'npm:css-element-queries'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular-in-memory-web-api': {
          main: './index.js',
          defaultExtension: 'js'
      },
      'ng2-bootstrap': {
        format: 'cjs',
        main: 'bundles/ng2-bootstrap.umd.js',
        defaultExtension: 'js'
      },
      'primeng': {
        defaultExtension: 'js'
      },
      'pdfjs-dist': {
        defaultExtension: 'js'
      },
      'angular2-toaster': {
        defaultExtension: 'js'
      },
      'css-element-queries': {
        defaultExtension: 'js'
      }
    }
  });
})(this);
```

I am receiving these errors:

```
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-bootstrap/accordion.js
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-bootstrap/accordion.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/node_modules/ng2-bootstrap/accordion.js as "./accordion" from http://localhost:3000/node_modules/ng2-bootstrap/index.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/node_modules/ng2-bootstrap/accordion.js as "./accordion" from http://localhost:3000/node_modules/ng2-bootstrap/index.js
```

Along with this error for every component:

`GET http://localhost:3000/node_modules/ng2-bootstrap/alert.js 404 (Not Found)`
