### ISSUE TITLE
Not able to run in prod mode

### ISSUE THREAD

**Issue by tushar-velingkar** [valor-software/ngx-bootstrap#1584]
Getting following errors when trying to run command : ionic run android --prod

I am trying to run my ionic app in production mode but getting these errors.
Ionic version 2.0.0
ng2-bootstrap version 1.3.2

```
can't resolve module /../node_modules/ng2-bootstrap/utils/linked-list.class.d.ts from /../node_modules/ng2-bootstrap/utils/linked-list.class.d.ts
[10:56:51]  build prod failed: can't find symbol LinkedList exported from module 
            /../node_modules/ng2-bootstrap/utils/linked-list.class.d.ts
[10:56:51]  ionic-app-script task: "build" 
[10:56:51]  Error: can't find symbol LinkedList exported from module 
            /../node_modules/ng2-bootstrap/utils/linked-list.class.d.ts
Error: can't find symbol LinkedList exported from module /../node_modules/ng2-bootstrap/utils/linked-list.class.d.ts
    at ReflectorHost.findDeclaration (/../node_modules/@angular/compiler-cli/src/reflector_host.js:173:23)
    at /../node_modules/@angular/compiler-cli/src/codegen.js:137:46
    at Array.forEach (native)
    at extractProgramSymbols (/../node_modules/@angular/compiler-cli/src/codegen.js:120:10)
    at CodeGenerator.codegen (/../node_modules/@angular/compiler-cli/src/codegen.js:57:29)
    at /../node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:51:34
```

**Comment by valorkin** [comment]
Gotcha missed it yesterday

**Comment by valorkin** [comment]
please try v1.3.3

**Comment by tushar-velingkar** [comment]
Its working. Thanks
