### ISSUE TITLE
Unexpected token export when importing ModalModule into ngModule declaration

### ISSUE THREAD

**Issue by 0radek** [valor-software/ngx-bootstrap#1589]
I am using angular@2.2.3 and ng2-bootstrap@1.3.2.  Please note I'm also using universal.  

In my ngModule declaration, I have:

```
import { ModalModule } from 'ng2-bootstrap/modal';

@NgModule({
  // other stuff
  imports: [
    ModalModule
  ]
})
```

Unfortunately, I am met with the following error:

```
/Users/scarywolfman/Work/universal/node_modules/ng2-bootstrap/modal/index.js:1
(function (exports, require, module, __filename, __dirname) { export { ModalBackdropComponent, ModalBackdropOptions } from './modal-backdrop.component';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.module.exports (/Users/scarywolfman/Work/universal/dist/server/server.bundle.js:4296:18)
    at __webpack_require__ (/Users/scarywolfman/Work/universal/dist/server/server.bundle.js:21:30)
```

Does anyone know how I can resolve this issue?  Do I need to upgrade webpack?  Thanks

**Comment by valorkin** [comment]
you need to use webpack 2 (ng-cli@>beta.26)
it will allow to tree shake
