### ISSUE TITLE
bs-sortable not working properly in lazy loaded modules

### ISSUE THREAD

**Issue by imixtron** [valor-software/ngx-bootstrap#1778]
I have 3 modules (for now) AppModule, AdminModule, SharedModule.
i have included the features i want to use from "**ng2-bootstrap**" inside SharedModule for example
```typescript
import { AlertModule, ModalModule, SortableModule, DropdownModule, TabsModule } from 'ng2-bootstrap';
@NgModule({
	declarations: [
                ...
		HeaderComponent,
	],
	imports: [
		...
                AlertModule.forRoot(),
		ModalModule.forRoot(),
		SortableModule.forRoot(),
		DropdownModule.forRoot(),
		TabsModule.forRoot(),
	],
	exports: [
                ...
		AlertModule,
		ModalModule,
		DropdownModule,
		TabsModule,
		SortableModule,
	]
})
```
sortable template:
```html
<bs-sortable
        [(ngModel)]="levels"
	itemClass="list-group-item"
	itemActiveClass="active"
	placeholderItem="Drag here"
	placeholderClass="placeholderStyle"
	wrapperClass="list-group"
></bs-sortable>
```
where
```typescript
    	levels: Array<string> = [
		"lorem",
		"ipsum",
		"dolor",
		"set",
		"amet"
	];
```

Everything is working fine, except for the SortableModule, whenever i add `[(ngModel)]` to the selector i get the following error

```error
EXCEPTION: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3
Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:124253:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:99136:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:10424:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:25245:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:60473:68)
    at http://localhost:4200/vendor.bundle.js:60356:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:60356:19)
    at createResult (http://localhost:4200/vendor.bundle.js:60238:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123625:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:36354:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123624:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:123421:43)
    at http://localhost:4200/vendor.bundle.js:123974:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:123658:31)
```
```error
EXCEPTION: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3
Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:124253:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:99136:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:10424:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:25245:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:60473:68)
    at http://localhost:4200/vendor.bundle.js:60356:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:60356:19)
    at createResult (http://localhost:4200/vendor.bundle.js:60238:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123625:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:36354:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123624:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:123421:43)
    at http://localhost:4200/vendor.bundle.js:123974:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:123658:31)
```
```
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3
Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:124253:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:99136:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:10424:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:25245:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:60473:68)
    at http://localhost:4200/vendor.bundle.js:60356:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:60356:19)
    at createResult (http://localhost:4200/vendor.bundle.js:60238:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123625:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:36354:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123624:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:123421:43)
    at http://localhost:4200/vendor.bundle.js:123974:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:123658:31)
    at resolvePromise (http://localhost:4200/vendor.bundle.js:123938:31) [angular]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:123914:17) [angular]
    at http://localhost:4200/vendor.bundle.js:123974:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:36345:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:123657:36) [angular]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:123461:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:123824:35) [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
```
```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3 ; Zone: angular ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortabl…, _nativeError: ZoneAwareError, __zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'ngMod…http://localhost:4200/vendor.bundle.js:123658:31)", __zone_symbol__message: "Template parse errors:↵Can't bind to 'ngModel' sin…ctiveClass="active"↵"): HierarchiesComponent@20:3"} Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'bs-sortable'.
1. If 'bs-sortable' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'bs-sortable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
		<div class="col-xs-12">
			<bs-sortable
			[ERROR ->][ngModel]="levels"
				itemClass="list-group-item"
				itemActiveClass="active"
"): HierarchiesComponent@20:3
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:124253:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:99136:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:10424:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:25245:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:60473:68)
    at http://localhost:4200/vendor.bundle.js:60356:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:60356:19)
    at createResult (http://localhost:4200/vendor.bundle.js:60238:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123625:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:36354:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:123624:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:123421:43)
    at http://localhost:4200/vendor.bundle.js:123974:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:123658:31)
```

also note that in non-lazy modules it is working perfectly fine. but in lazyLoaded modules with sharedModule it gives this exact error in this case `HierarchiesComponent` withing `AdminModule`. If i dont add `[(ngModel)]` the template is parsed as it should be, given as follows:

```Html
<bs-sortable _ngcontent-qrg-28="" itemactiveclass="active" itemclass="list-group-item" placeholderclass="placeholderStyle" placeholderitem="Drag here" wrapperclass="list-group" ng-reflect-wrapper-class="list-group" ng-reflect-item-class="list-group-item" ng-reflect-item-active-class="active" ng-reflect-placeholder-class="placeholderStyle" ng-reflect-placeholder-item="Drag here">
<div ng-reflect-ng-class="list-group" class="list-group" ng-reflect-ng-style="[object Object]">
  <!--template bindings={
  "ng-reflect-ng-if": null
}-->
    <!--template bindings={
  "ng-reflect-ng-for-of": null
}-->
</div>

<!--template bindings={}-->  
</bs-sortable>
```

**Comment by imixtron** [comment]
p.s. the issue occurs when the single module (SortableModule) is imported separately, it works when Ng2BootstrapModule is imported and exported.

**Comment by valorkin** [comment]
sortable is highly in experimental state and will change dramaticaly in next releases

**Comment by IlyaSurmay** [comment]
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by imixtron** [comment]
i was able to work around by importing CommonModule and changing the sharedModule structure. The project has ended now and the issue isn't relevant for me anymore. Thank you for your response.
