### ISSUE TITLE
Error happend when bulid --aot 

### ISSUE THREAD

**Issue by ginkosen** [valor-software/ngx-bootstrap#1892]
`
zone.js:522 Unhandled Promise rejection: this._state.isDisabledChange.filter is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: this._state.isDisabledChange.filter is not a function
    at e.Jkij.e.ngOnInit (bs-dropdown.directive.js:87)
    at e.ngDoCheck (bs-dropdown.directive.ngfactory.ts:97)
    at t.QSBR.t.detectChangesInternal (AccountInfoComponent.ngfactory.ts:326)
    at t.R2h3.t.detectChanges (view.js:425)
    at t.R2h3.t.internalDetectChanges (view.js:410)
    at t.XTOu.t.detectChangesInternal (BossComponent.ngfactory.ts:204)
    at t.R2h3.t.detectChanges (view.js:425)
    at t.R2h3.t.internalDetectChanges (view.js:410)
    at t.XTOu.t.detectChangesInternal (BossComponent.ngfactory.ts:84)
    at t.R2h3.t.detectChanges (view.js:425)
    at t.detectChanges (view_ref.js:170)
    at t.YfJG.t.activate (router_outlet.js:156)
    at t.placeComponentIntoOutlet (router.js:1350)
    at t.activateRoutes (router.js:1317)
    at router.js:1253 TypeError: this._state.isDisabledChange.filter is not a function
    at e.Jkij.e.ngOnInit (http://127.0.0.1:7002/ng/0.0d1b76c6584d8df3e977.chunk.js:1:669444)
    at e.ngDoCheck (http://127.0.0.1:7002/ng/0.0d1b76c6584d8df3e977.chunk.js:1:2106694)
    at t.QSBR.t.detectChangesInternal (http://127.0.0.1:7002/ng/0.0d1b76c6584d8df3e977.chunk.js:1:1200824)
    at t.R2h3.t.detectChanges (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:695:5749)
    at t.R2h3.t.internalDetectChanges (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:695:5542)
    at t.XTOu.t.detectChangesInternal (http://127.0.0.1:7002/ng/0.0d1b76c6584d8df3e977.chunk.js:1:1438512)
    at t.R2h3.t.detectChanges (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:695:5749)
    at t.R2h3.t.internalDetectChanges (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:695:5542)
    at t.XTOu.t.detectChangesInternal (http://127.0.0.1:7002/ng/0.0d1b76c6584d8df3e977.chunk.js:1:1434256)
    at t.R2h3.t.detectChanges (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:695:5749)
    at t.detectChanges (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:64:1302)
    at t.YfJG.t.activate (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:828:1956)
    at t.placeComponentIntoOutlet (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:148:14763)
    at t.activateRoutes (http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:148:14328)
    at http://127.0.0.1:7002/ng/vendor.5c9a3e604737b28ac638.bundle.js:148:13565
`

Code :
`
    BsDropdownDirective.prototype.ngOnInit = function () {
        var _this = this;
        // attach DOM listeners
        this._dropdown.listen({
            triggers: this.triggers,
            show: function () { return _this.show(); }
        });
        // set initial dropdown state from config
        this._state.autoClose = this._config.autoClose;
        // toggle visibility on toggle element click
        this._subscriptions.push(this._state
            .toggleClick.subscribe(function (value) { return _this.toggle(value); }));
        // hide dropdown if set disabled while opened
        this._subscriptions.push(this._state
            .isDisabledChange
            .filter(function (value) { return value === true; })
            .subscribe(function (value) { return _this.hide(); }));
    };
`

**Comment by valorkin** [comment]
There are were such issue, please install latest ngx-bootstrap
