### ISSUE TITLE
ngx-bootstrap/dropdown not working with angular2-universal

### ISSUE THREAD

**Issue by shijilesh** [valor-software/ngx-bootstrap#1928]
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';

@NgModule({
  imports: [BsDropdownModule.forRoot(),...]
})

is not working for me, throws error .

Exception: Call to Node module failed with error: Error: DI Error
at NoProviderError.Error (native)
at NoProviderError.ZoneAwareError (E:\Project\myapp\ClientApp\dist\vendor.js:74873:33)
at NoProviderError.BaseError [as constructor] (E:\Project\myapp\ClientApp\dist\vendor.js:1312:20)
at NoProviderError.AbstractProviderError [as constructor] (E:\Project\myapp\ClientApp\dist\vendor.js:1438:20)
at new NoProviderError (E:\Project\myapp\ClientApp\dist\vendor.js:1478:20)
at ReflectiveInjector_._throwOrNull (E:\Project\myapp\ClientApp\dist\vendor.js:3010:23)
at ReflectiveInjector_._getByKeyDefault (E:\Project\myapp\ClientApp\dist\vendor.js:3049:29)
at ReflectiveInjector_._getByKey (E:\Project\myapp\ClientApp\dist\vendor.js:2981:29)
at ReflectiveInjector_.get (E:\Project\myapp\ClientApp\dist\vendor.js:2850:25)
at NgModuleInjector.get (E:\Project\myapp\ClientApp\dist\vendor.js:8564:56)
at AppView.injectorGet (E:\Project\myapp\ClientApp\dist\vendor.js:12008:49)
at AppView.View_AppComponentx0.createInternal (/AppModule/AppComponentx/component.ngfactory.js:50:156)
at AppView.create (E:\Project\myapp\ClientApp\dist\vendor.js:11951:25)
at AppView.View_AppComponentx_Host0.createInternal (/AppModule/AppComponentx/host.ngfactory.js:15:19)
at AppView.createHostView (E:\Project\myapp\ClientApp\dist\vendor.js:11964:25)

**Comment by paesku** [comment]
there is a known issue here: https://github.com/valor-software/ngx-bootstrap/issues/1886

**Comment by valorkin** [comment]
error message not informative, which DI have failed?

**Comment by shijilesh** [comment]
Dear @valorkin,

I thinks its not similar issue of #1886 .I created asp core angular 2 application using yo generator-aspnetcore-spa http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/. and after imports: [BsDropdownModule.forRoot(), ] in module application doesn't works, recently ng2 bootstrap has changed to ngx bootstrap after that this issues is coming.

Thanks
Shijilesh

**Comment by viktorstaikov** [comment]
Hi guys,

I'm having the same problem using _ngx-bootstrap_ and _angular/universal-starter_. Neither of the modules I use (dropdown, carousel, modal) can be used.
I'm adding them as per documentation:
`
@NgModule({
  declarations: [AppComponent],
  imports: [
...
    BsDropdownModule.forRoot(),
    CarouselModule.forRoot(),
    ModalModule.forRoot(),
...
  ]
})
export class AppModule { }
`

The error is:
`
 throw new Error("Unexpected " + _this._getTypeDescriptor(importedType) + " '" + __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_4__facade_lang__["g" /* stringify */])(importedType) + "' imported by the module '" + __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_4__facade_lang__["g" /* stringify */])(moduleType) + "'");
                            ^

Error: Unexpected value '[object Object]' imported by the module 'AppModule'
`
Any ideas guys?

**Comment by halben** [comment]
+1

**Comment by valorkin** [comment]
are you speaking about this starter? https://github.com/angular/universal-starter/blob/master/package.json
if so it should not work with it because it has an outdated version of angular

if not, please drop a link to starter you are using

**Comment by halben** [comment]
see https://github.com/FrozenPandaz/ng-universal-demo

**Comment by shijilesh** [comment]
I solved the issue by upgrading to new version https://github.com/MarkPieszak/aspnetcore-angular2-universal. Seems I'm going to face so many issues in future, better to forget about server side prerendering and keep web api (asp core) separate and angular +webpack separate
