### ISSUE TITLE
Can not resolve all parameters for Rating

### ISSUE THREAD

**Issue by mohyeid** [valor-software/ngx-bootstrap#227]
I am using typescript plugin in eclipse and it does not do very good job with injectables. I get the following error when trying to use the Rating:

EXCEPTION: Cannot resolve all parameters for 'Rating'(@Self()). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Rating' is decorated with Injectable.
angular2.dev.js:23083 EXCEPTION: Cannot resolve all parameters for 'Rating'(@Self()). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Rating' is decorated with Injectable.BrowserDomAdapter.logError @ angular2.dev.js:23083BrowserDomAdapter.logGroup @ angular2.dev.js:23094ExceptionHandler.call @ angular2.dev.js:1185(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13515collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13419Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13438zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451(anonymous function) @ angular2-polyfills.js:123microtask @ angular2.dev.js:13470Zone.run @ angular2-polyfills.js:1243(anonymous function) @ angular2.dev.js:13438zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2.dev.js:23083 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1187(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13515collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13419Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13438zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451(anonymous function) @ angular2-polyfills.js:123microtask @ angular2.dev.js:13470Zone.run @ angular2-polyfills.js:1243(anonymous function) @ angular2.dev.js:13438zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2.dev.js:23083 Error: Cannot resolve all parameters for 'Rating'(@Self()). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Rating' is decorated with Injectable.
    at NoAnnotationError.BaseException [as constructor](http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:7351:21)
    at new NoAnnotationError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:1738:14)
    at _extractToken (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:9859:13)
    at http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:9818:14
    at Array.map (native)
    at Array.map (http://localhost:8080/Test/node_modules/es6-shim/es6-shim.min.js:10:17027)
    at _dependenciesFor (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:9817:19)
    at resolveFactory (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:9726:22)
    at Object.resolveProvider (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:9745:66)
    at Function.DirectiveProvider.createFromType (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:8638:27)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24316:60
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:13438:32)
    at zoneBoundFn (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:468:17)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at TemplateCompiler._compileComponentRuntime (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24307:14)
    at TemplateCompiler._compileNestedComponentRuntime (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24333:12)
    at http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24314:26
    at Array.forEach (native)
    at Array.forEach (http://localhost:8080/Test/node_modules/es6-shim/es6-shim.min.js:10:16878)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at TemplateCompiler._compileComponentRuntime (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24307:14)
    at TemplateCompiler.compileHostComponentRuntime (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24259:14)
    at RuntimeCompiler_.compileInHost (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24610:37)
    at DynamicComponentLoader_.loadNextToLocation (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:12385:29)
    at RouterOutlet.activate (http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:1966:27)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at RootRouter.Router.commit (http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2874:47)
    at RootRouter.commit (http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2989:45)
    at http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2779:26
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:13438:32)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2777:56
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:13438:32)
    at zoneBoundFn (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:468:17)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at RootRouter.Router._navigate (http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2773:10)
    at http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2750:24
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:13438:32)
    at zoneBoundFn (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2746:73
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:13438:32)
    at zoneBoundFn (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:468:17)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at RootRouter.Router.navigateByUrl (http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2743:64)
    at new RootRouter (http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:2977:12)
    at routerFactory (http://localhost:8080/Test/node_modules/angular2/bundles/router.dev.js:1295:22)
    at Injector._instantiate (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:11465:19)
    at Injector._instantiateProvider (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:11395:21)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then](http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at DynamicComponentLoader_.loadAsRoot (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:12355:49)
    at di_1.provide.useFactory (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:12453:39)
    at Injector._instantiate (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:11462:19)
    at Injector._instantiateProvider (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:11395:21)
    at Injector._new (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:11385:19)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://localhost:8080/Test/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at NgZone._createInnerZone (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:13426:39)
    at new NgZone (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:13292:32)
    at createNgZone (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:12475:12)
    at PlatformRef_.application (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:12550:31)
    at Object.bootstrap (http://localhost:8080/Test/node_modules/angular2/bundles/angular2.dev.js:24805:64)
    at execute (http://localhost:8080/Test/app/main.js:18:23)
    at ensureEvaluated (http://localhost:8080/Test/node_modules/systemjs/dist/system.src.js:3212:26)
    at Object.execute (http://localhost:8080/Test/node_modules/systemjs/dist/system.src.js:3330:13)BrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1188(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13515collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13419Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13438zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451(anonymous function) @ angular2-polyfills.js:123microtask @ angular2.dev.js:13470Zone.run @ angular2-polyfills.js:1243(anonymous function) @ angular2.dev.js:13438zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2.dev.js:23093 EXCEPTION: Cannot resolve all parameters for 'Rating'(@Self()). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Rating' is decorated with Injectable.

**Comment by valorkin** [comment]
The wall, please left only useful stack
Search in issues please, and check readme, something wrong with your config

**Comment by valorkin** [comment]
closing for no additional details
