### ISSUE TITLE
BsDatepickerModule - Unhandled Promise rejection: Template parse errors:

### ISSUE THREAD

**Issue by ddivita** [valor-software/ngx-bootstrap#2854]
ngx-bootstrap v. 1.9.3 
angular 4.1.3 

I am thinking there may be conflict with another library. I read a few posts that duplicate selectors could cause this error, but I am not really sure.  The issue I am having, is when I add the module to my `app.module.ts` and run the application I receive the error upon startup. At this point I have not added the directive to any page. Once I remove the module and rerun my app it works fine. 

These are the moduals I am using:
`import { CollapseModule, BsDropdownModule, TypeaheadModule, ModalModule, TabsModule, BsDatepickerModule  } from 'ngx-bootstrap';`

My imports section:
```
...
BsDatepickerModule.forRoot(),
...
```
I hoping there is something I am missing.

**Comment by IlyaSurmay** [comment]
Hi, what error do you receive? Also could you create a plunkr/stackblitz with reproduction? That would be helpful

**Comment by ddivita** [comment]
The error message is in the title. I'll try to replicate this in a plunkr. Here is the entire trace:
```

Unhandled Promise rejection: Template parse errors:
'comcept-app' is not a known element:
1. If 'comcept-app' is an Angular component, then verify that it is part of this module.
2. If 'comcept-app' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</head>
<body class="top-navbar-fixed">
    [ERROR ->]<comcept-app>
        <div class="block-ui-wrapper active">
            <div class="block-ui-spinne"): ng:///bs-datepicker-view.html@42:4 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
'comcept-app' is not a known element:
1. If 'comcept-app' is an Angular component, then verify that it is part of this module.
2. If 'comcept-app' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</head>
<body class="top-navbar-fixed">
    [ERROR ->]<comcept-app>
        <div class="block-ui-wrapper active">
            <div class="block-ui-spinne"): ng:///bs-datepicker-view.html@42:4
    at syntaxError (compiler.es5.js:1544)
    at TemplateParser.parse (compiler.es5.js:12034)
    at JitCompiler._compileTemplate (compiler.es5.js:25787)
    at eval (compiler.es5.js:25707)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.es5.js:25707)
    at createResult (compiler.es5.js:25596)
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:141)
    at zone.js:831 Error: Template parse errors:
'comcept-app' is not a known element:
1. If 'comcept-app' is an Angular component, then verify that it is part of this module.
2. If 'comcept-app' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</head>
<body class="top-navbar-fixed">
    [ERROR ->]<comcept-app>
        <div class="block-ui-wrapper active">
            <div class="block-ui-spinne"): ng:///bs-datepicker-view.html@42:4
    at syntaxError (http://localhost:65388/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at TemplateParser.parse (http://localhost:65388/node_modules/@angular/compiler/bundles/compiler.umd.js:12041:19)
    at JitCompiler._compileTemplate (http://localhost:65388/node_modules/@angular/compiler/bundles/compiler.umd.js:25792:39)
    at eval (http://localhost:65388/node_modules/@angular/compiler/bundles/compiler.umd.js:25716:62)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:65388/node_modules/@angular/compiler/bundles/compiler.umd.js:25716:19)
    at createResult (http://localhost:65388/node_modules/@angular/compiler/bundles/compiler.umd.js:25601:19)
    at ZoneDelegate.invoke (http://localhost:65388/node_modules/zone.js/dist/zone.js:391:26)
    at Zone.run (http://localhost:65388/node_modules/zone.js/dist/zone.js:141:43)
    at http://localhost:65388/node_modules/zone.js/dist/zone.js:831:57
```

**Comment by ddivita** [comment]
I updated angular 4.4.5 and still have the issue.

**Comment by IlyaSurmay** [comment]
Are you sure this is related to ngx-bootstrap?
Error says that you `'comcept-app' is not a known element`.
Also could you create a plunkr/stackblitz with reproduction?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-stack?file=app%2Fapp.module.ts

**Comment by ddivita** [comment]
Again, I only see the error once I add the BsDatepickerModule component to my app.module.ts and run the app. Once it is removed I can run fine. There is also this inside the error message:
`ng:///bs-datepicker-view.html@42:4`

I am only guessing it is some sort of conflict with another component, but I can add any of the other bootstrap module without any issue. Something is unique to the BsDatepickerModule. I just can't nail it down. I need to replicate my packages on plunkr. I'll try to get it in today.

**Comment by GrumpyGoslin** [comment]
I am having the same issue
```

zone.js:522 Unhandled Promise rejection: Template parse errors:
'my-app' is not a known element:
1. If 'my-app' is an Angular component, then verify that it is part of this module.
2. If 'my-app' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("cript><script>System.import('').catch(function (err) { console.error(err); });</script></head><body>[ERROR ->]<my-app></my-app></body><!-- jQuery--><script src="/node_modules/jquery/dist/jquery.min.js"></script>"): BsDatepickerContainerComponent@0:1727 ; Zone: <root> ; Task: Promise.then ; Value: 
```

**Comment by ddivita** [comment]
@GrumpyGoslin, no i did not. I ended up having to use another library for now.  I am curious to know what other components you may be using. I wonder if it is a conflict. Here is my packages.json

```
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation for visual studio 2017 & WebApi",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "pree2e": "webdriver-manager update",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "^4.4.5",
    "@angular/common": "^4.4.5",
    "@angular/compiler": "^4.4.5",
    "@angular/core": "^4.4.5",
    "@angular/forms": "^4.4.5",
    "@angular/http": "^4.4.5",
    "@angular/platform-browser": "^4.4.5",
    "@angular/platform-browser-dynamic": "^4.4.5",
    "@angular/platform-server": "^4.4.5",
    "@angular/router": "^4.4.5",
    "@types/jquery": "^2.0.48",
    "@types/underscore": "^1.8.1",
    "@types/vkbeautify": "^0.99.1",
    "angular": "^1.6.6",
    "angular-datatables": "^4.2.0",
    "angular-in-memory-web-api": "^0.2.5",
    "angular2-notifications": "^0.7.7",
    "core-js": "^2.5.0",
    "es6-shim": "0.35.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "lodash.clonedeep": "^4.5.0",
    "lodash.differencewith": "^4.5.0",
    "lodash.find": "^4.6.0",
    "lodash.isequal": "^4.5.0",
    "moment": "^2.18.1",
    "ng-block-ui": "^1.0.0-beta.14",
    "ng-selectize": "^1.0.11",
    "ng2-toasty": "^4.0.3",
    "ngx-bootstrap": "^1.9.3",
    "primeng": "^4.2.2",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.2",
    "selectize": "^0.12.4",
    "systemjs": "^0.20.17",
    "typescript": "^2.4.2",
    "underscore": "^1.8.3",
    "vkbeautify": "^0.99.3",
    "zone.js": "^0.8.16"
  },
  "devDependencies": {
    "@types/datatables.net": "^1.10.1",
    "@types/jasmine": "2.5.36",
    "@types/jquery": "^2.0.45",
    "@types/node": "^6.0.46",
    "canonical-path": "0.0.2",
    "concurrently": "^3.2.0",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "typescript": "~2.0.10"
  },
  "repository": {}
}
```

**Comment by valorkin** [comment]
Seems there are promise in bs modal container component, not returned and without then/catch
Tslint rule should complain about it, but it doesn't

**Comment by IlyaSurmay** [comment]
Try ngx-bootstrap@2.0.0-beta.8, `bs-datepicker-view.html` error is fixed there
