### ISSUE TITLE
ModalDirective.show() Angular Universal

### ISSUE THREAD

**Issue by matthewwren** [valor-software/ngx-bootstrap#3080]
I am using ModalDirective in version 1.9.3 and am using Angular 4. When a call is made to show() when code is executing on the server side (I am using Angular Universal), I am getting the following exception.  On the server side 'document' doesn't exist (unless there is some module I should be using to mimic this?) - or is this just a limitation of ModalDirective that it can't run on the server side?

Cannot read property 'body' of undefined
TypeError: Cannot read property 'body' of undefined
at ModalDirective.checkScrollbar (ClientApp\dist\main-server.js:49156:105)
at ModalDirective.show (ClientApp\dist\main-server.js:48977:14)
at ConfirmModalComponent.show (ClientApp\dist\main-server.js:48086:27)
at SafeSubscriber._error (ClientApp\dist\main-server.js:87270:41)
at SafeSubscriber.module.exports.SafeSubscriber.__tryOrUnsub (ClientApp\dist\vendor.js:574:16)
at SafeSubscriber.module.exports.SafeSubscriber.error (ClientApp\dist\vendor.js:533:26)
at Subscriber.module.exports.Subscriber._error (ClientApp\dist\vendor.js:464:26)
at Subscriber.module.exports.Subscriber.error (ClientApp\dist\vendor.js:438:18)
at MapSubscriber.module.exports.Subscriber._error (ClientApp\dist\vendor.js:464:26)
at MapSubscriber.module.exports.Subscriber.error (ClientApp\dist\vendor.js:438:18)

**Comment by IlyaSurmay** [comment]
Hi! There's no need to create an issue here if you've already asked for a help on stackoverflow https://stackoverflow.com/questions/47399841/modaldirective-causing-error-in-angular-universal
I answered you there.
