### ISSUE TITLE
Cannot Build ngx-bootstrap-base@2.0.0-beta.10 On macOS 10.13.1

### ISSUE THREAD

**Issue by rls1955** [valor-software/ngx-bootstrap#3208]
Have a chronic problem building the latest version:   "name": "ngx-bootstrap-base",
  "version": "2.0.0-beta.10", 
Using macOS High Sierra 10.13.1 and NetBeans 8.2 with Node.js and npm plugins.
node: v8.9.1
npm: v5.5.1

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: "ngx-bootstrap-base", "version": "2.0.0-beta.10"

Angular:     "@angular/common": "4.3.6",

Bootstrap:    "bootstrap": "3.3.7",

### Build system:   "@angular/cli": "1.5.0",

Below is the output from the "npm Install" from the NetBeans IDE but error is the same from Terminal window:

"/bin/bash" "-lc" "\"/usr/local/bin/npm\" \"run-script\" \"start\""

> ngx-bootstrap-base@2.0.0-beta.10 start /Users/xx/Downloads/ngx-bootstrap-development-4
> ng serve --aot --host 0.0.0.0

** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **

ERROR in ./demo/src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/randysmith/Downloads/ngx-bootstrap-development-4/demo/src'
resolve './$$_gendir/app/app.module.ngfactory' in '/Users/xx/Downloads/ngx-bootstrap-development-4/demo/src'
  using description file: /Users/xx/Downloads/ngx-bootstrap-development-4/package.json (relative path: ./demo/src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/xx/Downloads/ngx-bootstrap-development-4/package.json (relative path: ./demo/src)
    using description file: /Users/xx/Downloads/ngx-bootstrap-development-4/package.json (relative path: ./demo/src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/randysmith/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/xx/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/xx/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/xx/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory doesn't exist
[/Users/randysmith/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory]
[/Users/randysmith/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory.ts]
[/Users/randysmith/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory.js]
[/Users/randysmith/Downloads/ngx-bootstrap-development-4/demo/src/$$_gendir/app/app.module.ngfactory]
 @ ./demo/src/main.ts 6:29-76
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./demo/src/main.ts
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ngx-bootstrap/tabs relative to /Users/xx/Downloads/ngx-bootstrap-development-4/demo/src/app/docs/api-docs/index.ts., resolving symbol NgApiDocModule in /Users/xx/Downloads/ngx-bootstrap-development-4/demo/src/app/docs/api-docs/index.ts, resolving symbol NgApiDocModule in /Users/xx/Downloads/ngx-bootstrap-development-4/demo/src/app/docs/api-docs/index.ts
    at syntaxError (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
    at simplifyInContext (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24949:23)
    at StaticReflector.simplify (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24961:13)
    at StaticReflector.annotations (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24391:41)
    at NgModuleResolver.resolve (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:14733:70)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:15386:60)
    at addNgModule (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:58)
    at /Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24252:14
    at Array.forEach (<anonymous>)
    at _createNgModules (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24251:26)
    at analyzeNgModules (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24126:14)
    at analyzeAndValidateNgModules (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:24136:35)
    at AotCompiler.analyzeModulesAsync (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler/bundles/compiler.umd.js:23772:46)
    at CodeGenerator.codegen (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/Users/xx/Downloads/ngx-bootstrap-development-4/node_modules/@ngtools/webpack/src/plugin.js:430:58)

Date: 2017-12-06T14:45:27.456Z
Hash: dc73821707cc0b0ad8c4
Time: 3530ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 13.6 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 1.5 MB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 154 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 4.74 MB [initial] [rendered]
webpack: Failed to compile.

**Comment by valorkin** [comment]
npm run build
npm run link
ng serve

Join slack :)

**Comment by rls1955** [comment]
Was able to build and run!!! :-) 👍 
****Notes for macOS**:**
- Used a terminal window not NetBeans 8.2 with plug-ins.
- Switched to root
- Did npm Install to create node_modules
- Did npm run build. Was ok with some warnings...
- Did npm run link. Was ok
- Did ng serve but it said "No such command"
- Did npm start which was successful but with warning message  "webpack: Compiled with warnings."
- http://localhost:4200/ is up and running. 👍

**Comment by valorkin** [comment]
Awesome:)
