### ISSUE TITLE
Deploying Angular 5 App on firebase.

### ISSUE THREAD

**Issue by ahsanshafiqe** [valor-software/ngx-bootstrap#3833]
Getting error while deploying app on firebase, please suggest solution. 

=== Deploying to 'customerweb'...

i  deploying functions, hosting
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

D:\work\CustomerWeb\functions\node_modules\ngx-bootstrap\progressbar\progressbar.component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, HostBinding, Input } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.Wpl1 (D:\work\CustomerWeb\functions\dist\server\main.bundle.js:1:68325)

### Versions of ngx-bootstrap, Angular, and Bootstrap:
"@angular" 5.2.3
   "bootstrap": "^4.0.0",
    "core-js": "^2.4.1",
    "express": "^4.16.2",
    "ngx-bootstrap": "^2.0.2",

**Comment by IlyaSurmay** [comment]
Maybe this is related to #2369
