### ISSUE TITLE
Problem with ngFormControl and TypeAhead Input

### ISSUE THREAD

**Issue by Jeetah** [valor-software/ngx-bootstrap#463]
If combining 

`<input autocomplete="off" type="text" class="form-control" id="mainPLZ" placeholder="PLZ"
                   [ngFormControl]="zipControl"
                   [(ngModel)]="registrationForm.mainPersonStay.person.address.zip"
                   [typeahead]="searchAsyncZipRef"`...

NG2 reports some crazy error regarding missing provider (although NgModel is used on various form elements before - so definitely there):

ORIGINAL EXCEPTION: No provider for NgModel!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor](http://localhost:8080/connect-host/node_modules/angular2/bundles/angular2.dev.js:5491:21)
    at NoProviderError.AbstractProviderError [as constructor](http://localhost:8080/connect-host/node_modules/angular2/bundles/angular2.dev.js:1596:14)
    at new NoProviderError (http://localhost:8080/connect-host/node_modules/angular2/bundles/angular2.dev.js:1620:14)
    at ReflectiveInjector_._throwOrNull (http://localhost:8080/connect-host/node_modules/angular2/bundles/angular2.dev.js:6961:15)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8080/connect-host/node_modules/angular2/bundles/angular2.dev.js:6985:21)
    at ReflectiveInjector_._getByKey (http://localhost:8080/connect-host/node_modules/angular2/bundles/angular2.dev.js:6954:21)

Without NgFormControl binding everything works as expected...

**Comment by slintes** [comment]
this workaround worked for me: https://github.com/valor-software/ng2-bootstrap/issues/92#issuecomment-198986011
there is another one 3 comments later, but that didn't work for me...

**Comment by Jeetah** [comment]
Not really a workaround since this requires changing the library source - which is not possible if using build pipeline that pulls this each time new...(and we don't want to version npm modules)

**Comment by slintes** [comment]
yes, I know, and I'm really annoyed by this too. There is a PR open since a while (https://github.com/valor-software/ng2-bootstrap/pull/396). Until it get's merged, or there is another solution, I copied the complete (fixed) ng2-bootstrap code into my project's source directory (so outside of node_modules), removed it from package.json and changed imports. This way I get it through our build pipeline. Another ugly workaround, but it works...

**Comment by slintes** [comment]
I think this can be closed like #92

**Comment by adrianfaciu** [comment]
Until the fix gets merged you can also create a custom build, use [npm pack](https://docs.npmjs.com/cli/pack) inside ng2-bootstrap and configure npm to install the library from the resulting tarball. In this way one needs to add only one single file to the project. Depends on what you prefer.
