### ISSUE TITLE
Tooltip: Error during evaluation of "mouseenter"

### ISSUE THREAD

**Issue by theunreal** [valor-software/ngx-bootstrap#468]
When I mouse over my image:
`<img src="{{myimage}}" tooltip="I can have a custom class applied to me!" tooltipClass="customClass">`

I get this:

EXCEPTION: Error during evaluation of "mouseenter"
angular2.dev.js:23941 EXCEPTION: Error during evaluation of "mouseenter"BrowserDomAdapter.logError @ angular2.dev.js:23941BrowserDomAdapter.logGroup @ angular2.dev.js:23952ExceptionHandler.call @ angular2.dev.js:1317(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Subscriber.ts:181SafeSubscriber.next @ Subscriber.ts:133Subscriber._next @ Subscriber.ts:83Subscriber.next @ Subscriber.ts:56Subject._finalNext @ Subject.ts:150Subject._next @ Subject.ts:140Subject.next @ Subject.ts:86EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.dev.js:2140NgZone.run @ angular2.dev.js:13649outsideHandler @ angular2.dev.js:13495ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263ZoneTask.invoke @ angular2-polyfills.js:431
angular2.dev.js:23941 ORIGINAL EXCEPTION: TypeError: Cannot read property 'resolve' of undefinedBrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1326(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Subscriber.ts:181SafeSubscriber.next @ Subscriber.ts:133Subscriber._next @ Subscriber.ts:83Subscriber.next @ Subscriber.ts:56Subject._finalNext @ Subject.ts:150Subject._next @ Subject.ts:140Subject.next @ Subject.ts:86EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.dev.js:2140NgZone.run @ angular2.dev.js:13649outsideHandler @ angular2.dev.js:13495ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263ZoneTask.invoke @ angular2-polyfills.js:431
angular2.dev.js:23941 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1329(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Subscriber.ts:181SafeSubscriber.next @ Subscriber.ts:133Subscriber._next @ Subscriber.ts:83Subscriber.next @ Subscriber.ts:56Subject._finalNext @ Subject.ts:150Subject._next @ Subject.ts:140Subject.next @ Subject.ts:86EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.dev.js:2140NgZone.run @ angular2.dev.js:13649outsideHandler @ angular2.dev.js:13495ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263ZoneTask.invoke @ angular2-polyfills.js:431
angular2.dev.js:23941 TypeError: Cannot read property 'resolve' of undefined
    at TooltipDirective.show (ng2-bootstrap.min.js:4)
    at AbstractChangeDetector.ChangeDetector_FightComponent_4.handleEventInternal (viewFactory_FightComponent:1749)
    at AbstractChangeDetector.handleEvent (angular2.dev.js:9568)
    at AppView.triggerEventHandlers (angular2.dev.js:10246)
    at eval (viewFactory_FightComponent:2877)
    at angular2.dev.js:14068
    at angular2.dev.js:13496
    at ZoneDelegate.invoke (angular2-polyfills.js:332)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (angular2.dev.js:2111)
    at ZoneDelegate.invoke (angular2-polyfills.js:331)BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1330(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Subscriber.ts:181SafeSubscriber.next @ Subscriber.ts:133Subscriber._next @ Subscriber.ts:83Subscriber.next @ Subscriber.ts:56Subject._finalNext @ Subject.ts:150Subject._next @ Subject.ts:140Subject.next @ Subject.ts:86EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.dev.js:2140NgZone.run @ angular2.dev.js:13649outsideHandler @ angular2.dev.js:13495ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263ZoneTask.invoke @ angular2-polyfills.js:431
angular2.dev.js:23941 ERROR CONTEXT:BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1333(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Subscriber.ts:181SafeSubscriber.next @ Subscriber.ts:133Subscriber._next @ Subscriber.ts:83Subscriber.next @ Subscriber.ts:56Subject._finalNext @ Subject.ts:150Subject._next @ Subject.ts:140Subject.next @ Subject.ts:86EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.dev.js:2140NgZone.run @ angular2.dev.js:13649outsideHandler @ angular2.dev.js:13495ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263ZoneTask.invoke @ angular2-polyfills.js:431
angular2.dev.js:23941 EventEvaluationErrorContext {element: img, componentElement: comment, context: FightComponent, locals: Object, injector: Injector}BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1334(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Subscriber.ts:181SafeSubscriber.next @ Subscriber.ts:133Subscriber._next @ Subscriber.ts:83Subscriber.next @ Subscriber.ts:56Subject._finalNext @ Subject.ts:150Subject._next @ Subject.ts:140Subject.next @ Subject.ts:86EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.dev.js:2140NgZone.run @ angular2.dev.js:13649outsideHandler @ angular2.dev.js:13495ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263ZoneTask.invoke @ angular2-polyfills.js:431
angular2-polyfills.js:267 Uncaught EXCEPTION: Error during evaluation of "mouseenter"
ORIGINAL EXCEPTION: TypeError: Cannot read property 'resolve' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'resolve' of undefined
    at TooltipDirective.show (http://localhost:3000/node_modules/ng2-bootstrap/bundles/ng2-bootstrap.min.js:4:27722)
    at AbstractChangeDetector.ChangeDetector_FightComponent_4.handleEventInternal (viewFactory_FightComponent:1749:32)
    at AbstractChangeDetector.handleEvent (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9568:25)
    at AppView.triggerEventHandlers (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:10246:34)
    at eval (viewFactory_FightComponent:2877:121)
    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:14068:34
    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13496:18
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:332:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:2111:31)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:331:35)
ERROR CONTEXT:
[object Object]

**Comment by valorkin** [comment]
Plunkr with reproduce please

**Comment by theunreal** [comment]
Seem like it was conflicted with another package, I think ng-2 material.

**Comment by valorkin** [comment]
He, that's interesting
