### ISSUE TITLE
Exception when using tabs

### ISSUE THREAD

**Issue by jhiemer** [valor-software/ngx-bootstrap#52]
Hi,
I am trying to use the tabs. When I load the page with the tabs I get:

``` trace
EXCEPTION: Expression 'classMap in Tabset@1:20' has changed after it was checked. Previous value: '[object Object]'. Current value: '[object Object]' in [classMap in Tabset@1:20]BrowserDomAdapter.logError @ angular2.dev.js:23514BrowserDomAdapter.logGroup @ angular2.dev.js:23525ExceptionHandler.call @ angular2.dev.js:1145(anonymous function) @ angular2.dev.js:14801NgZone._notifyOnError @ angular2.dev.js:5796collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:5700r.run @ angular2-polyfills.min.js:1(anonymous function) @ angular2.dev.js:5719NgZone.run @ angular2.dev.js:5681(anonymous function) @ angular2.dev.js:14884schedulerFn @ angular2.dev.js:14385t @ tryOrOnError.js:4t.next @ Subscriber.js:112t._next @ Subject.js:111t.next @ Subject.js:74EventEmitter.emit @ angular2.dev.js:14366(anonymous function) @ angular2.dev.js:5612r.run @ angular2-polyfills.min.js:1NgZone._notifyOnTurnDone @ angular2.dev.js:5611(anonymous function) @ angular2.dev.js:5726NgZone.run @ angular2.dev.js:5681(anonymous function) @ angular2.dev.js:14884schedulerFn @ angular2.dev.js:14385t @ tryOrOnError.js:4t.next @ Subscriber.js:112t._next @ Subject.js:111t.next @ Subject.js:74EventEmitter.emit @ angular2.dev.js:14366(anonymous function) @ angular2.dev.js:5612r.run @ angular2-polyfills.min.js:1NgZone._notifyOnTurnDone @ angular2.dev.js:5611(anonymous function) @ angular2.dev.js:5726(anonymous function) @ angular2-polyfills.min.js:1
angular2.dev.js:23514 ORIGINAL EXCEPTION: Expression 'classMap in Tabset@1:20' has changed after it was checked. Previous value: '[object Object]'. Current value: '[object Object]'BrowserDomAdapter.logError @ angular2.dev.js:23514ExceptionHandler.call @ angular2.dev.js:1154(anonymous function) @ angular2.dev.js:14801NgZone._notifyOnError @ angular2.dev.js:5796collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:5700r.run @ angular2-polyfills.min.js:1(anonymous function) @ angular2.dev.js:5719NgZone.run @ angular2.dev.js:5681(anonymous function) @ angular2.dev.js:14884schedulerFn @ angular2.dev.js:14385t @ tryOrOnError.js:4t.next @ Subscriber.js:112t._next @ Subject.js:111t.next @ Subject.js:74EventEmitter.emit @ angular2.dev.js:14366(anonymous function) @ angular2.dev.js:5612r.run @ angular2-polyfills.min.js:1NgZone._notifyOnTurnDone @ angular2.dev.js:5611(anonymous function) @ angular2.dev.js:5726NgZone.run @ angular2.dev.js:5681(anonymous function) @ angular2.dev.js:14884schedulerFn @ angular2.dev.js:14385t @ tryOrOnError.js:4t.next @ Subscriber.js:112t._next @ Subject.js:111t.next @ Subject.js:74EventEmitter.emit @ angular2.dev.js:14366(anonymous function) @ angular2.dev.js:5612r.run @ angular2-polyfills.min.js:1NgZone._notifyOnTurnDone @ angular2.dev.js:5611(anonymous function) @ angular2.dev.js:5726(anonymous function) @ angular2-polyfills.min.js:1
angular2.dev.js:23514 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23514ExceptionHandler.call @ angular2.dev.js:1157(anonymous function) @ angular2.dev.js:14801NgZone._notifyOnError @ angular2.dev.js:5796collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:5700r.run @ angular2-polyfills.min.js:1(anonymous function) @ angular2.dev.js:5719NgZone.run @ angular2.dev.js:5681(anonymous function) @ angular2.dev.js:14884schedulerFn @ angular2.dev.js:14385t @ tryOrOnError.js:4t.next @ Subscriber.js:112t._next @ Subject.js:111t.next @ Subject.js:74EventEmitter.emit @ angular2.dev.js:14366(anonymous function) @ angular2.dev.js:5612r.run @ angular2-polyfills.min.js:1NgZone._notifyOnTurnDone @ angular2.dev.js:5611(anonymous function) @ angular2.dev.js:5726NgZone.run @ angular2.dev.js:5681(anonymous function) @ angular2.dev.js:14884schedulerFn @ angular2.dev.js:14385t @ tryOrOnError.js:4t.next @ Subscriber.js:112t._next @ Subject.js:111t.next @ Subject.js:74EventEmitter.emit @ angular2.dev.js:14366(anonymous function) @ angular2.dev.js:5612r.run @ angular2-polyfills.min.js:1NgZone._notifyOnTurnDone @ angular2.dev.js:5611(anonymous function) @ angular2.dev.js:5726(anonymous function) @ angular2-polyfills.min.js:1
angular2.dev.js:23514 Error: Expression 'classMap in Tabset@1:20' has changed after it was checked. Previous value: '[object Object]'. Current value: '[object Object]'
    at ExpressionChangedAfterItHasBeenCheckedException.BaseException [as constructor] (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8080:21)
    at new ExpressionChangedAfterItHasBeenCheckedException (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:4653:14)
    at AbstractChangeDetector.throwOnChangeError (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8982:13)
    at AbstractChangeDetector.ChangeDetector_Tabset_0.detectChangesInRecordsInternal (eval at <anonymous> (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:10897:14), <anonymous>:30:16)
    at AbstractChangeDetector.detectChangesInRecords (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8824:14)
    at AbstractChangeDetector.runDetectChanges (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8807:12)
    at AbstractChangeDetector._detectChangesInViewChildren (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8877:14)
    at AbstractChangeDetector.runDetectChanges (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8811:12)
    at AbstractChangeDetector._detectChangesContentChildren (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8871:14)
    at AbstractChangeDetector.runDetectChanges (http://127.0.0.1:8001/node_modules/angular2/bundles/angular2.dev.js:8808:12)
```

Do you have any idea what is causing the problem?

**Comment by jhiemer** [comment]
Found solved with latest commit. Excuse the noise.

**Comment by valorkin** [comment]
Thanks for report, drop any issues you have found
