### ISSUE TITLE
model undefined in typeahead

### ISSUE THREAD

**Issue by fdu-axiometrics** [valor-software/ngx-bootstrap#528]
I got following error when using typeahead directive.

this.cd.model is undefined in onChange function. Please take a look at the following stacktrace for details.

ORIGINAL EXCEPTION: TypeError: Cannot read property 'toString' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'toString' of undefined
    at TypeaheadDirective.onChange (http://localhost:3000/main.bundle.js:68925:27)
    at DebugAppView._View_AdvancedSearchComponent5._handle_keyup_0_4 (AdvancedSearchComponent.template.js:1216:45)
    at http://localhost:3000/main.bundle.js:102078:25
    at http://localhost:3000/main.bundle.js:55344:37
    at http://localhost:3000/main.bundle.js:55407:94
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:8053:30)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/main.bundle.js:53624:42)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:8052:36)
    at Zone.runGuarded (http://localhost:3000/polyfills.bundle.js:7960:49)
    at NgZoneImpl.runInnerGuarded (http://localhost:3000/main.bundle.js:53657:79)
    at NgZone.runGuarded (http://localhost:3000/main.bundle.js:38832:74)
    at HTMLInputElement.outsideHandler (http://localhost:3000/main.bundle.js:55407:62)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:8086:39)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:7983:49)
    at HTMLInputElement.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:8153:35)
ERROR CONTEXT:

**Comment by zaidchauhan** [comment]
@fdu-axiometrics Did you find any solution to this ?

**Comment by fdu-axiometrics** [comment]
define ng-model in your component before using it.

```
private data: any;

<input ... [(ngModel)]="data">
```
