### ISSUE TITLE
rc.6  Unexpected token export(…)  error...

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#913]
```
index.html:51 Error: (SystemJS) SyntaxError: Unexpected token export(…) "error system.js Error: (SystemJS) SyntaxError: Unexpected token export
        at Object.eval (http://localhost:8080/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js:2:14)
        at eval (http://localhost:8080/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js:29:4)
        at eval (http://localhost:8080/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js:30:3)
    Evaluating http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.6/src/facade/lang.js
    Evaluating http://localhost:8080/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js
    Evaluating http://localhost:8080/jspm_packages/npm/ng2-bootstrap@1.1.0/components/carousel/carousel.component.js
    Evaluating http://localhost:8080/jspm_packages/npm/ng2-bootstrap@1.1.0/components/carousel.js
    Evaluating http://localhost:8080/jspm_packages/npm/ng2-bootstrap@1.1.0/ng2-bootstrap.js
    Error loading http://localhost:8080/src/App.ts"
```

re-opening bug so we can track,

tx

Sean

**Comment by Martin-Luft** [comment]
As I already said in https://github.com/valor-software/ng2-bootstrap/issues/912, this is fixed in master branch but not yet released. Hopefully @valorkin will publish a new release today _pray_
